import { DEMO_CLIENT } from './matching.constants';
import type { FreelancerProfile, Job } from './matching.types';

function photo(seed: string): string {
  return `https://i.pravatar.cc/800?u=${encodeURIComponent(seed)}`;
}

export const MOCK_FREELANCERS: FreelancerProfile[] = [
  {
    id: 'fl-mike',
    userId: 'user-mike',
    name: 'Mike',
    profilePhoto: photo('mike-mechanic'),
    verified: true,
    category: 'motorbike_mechanic',
    skills: ['Motorcycle repair', 'Vespa', 'European motorcycles', 'Piaggio', 'Diagnostics'],
    location: 'Bangkok',
    province: 'Bangkok',
    yearsExperience: 5,
    rating: 4.9,
    completedJobs: 86,
    hourlyRate: 450,
    monthlyRate: 20_000,
    availability: 'available_now',
    languages: ['English', 'Thai'],
    certifications: ['OEM Vespa service', 'Thai motorcycle technician'],
    responseRate: 98,
    bio: 'Bangkok-based mechanic specializing in Vespa GTS and European scooters. Same-day inspections and honest diagnostics.',
    preferredJobTypes: ['Vespa service', 'Scooter repair', 'On-site mechanic'],
    remoteOk: false,
    responseTime: 'Usually replies in 15 minutes',
    autoAcceptThreshold: 82,
    reviews: [
      { id: 'r1', author: 'James D.', rating: 5, text: 'Fixed my GTS 300 the same afternoon. Clear pricing.', date: '2026-07-12' },
      { id: 'r2', author: 'Ploy S.', rating: 5, text: 'Knew exactly what the Vespa needed. Highly recommend.', date: '2026-05-02' },
    ],
    portfolio: [
      { id: 'p1', title: 'Vespa GTS 300 major service', description: 'Belt, rollers, fluids, and brake inspection in Sukhumvit.' },
      { id: 'p2', title: 'European scooter electrics', description: 'Diagnosed charging issue on a Piaggio Beverly.' },
    ],
  },
  {
    id: 'fl-somchai',
    userId: 'user-somchai',
    name: 'Somchai',
    profilePhoto: photo('somchai-mechanic'),
    verified: true,
    category: 'motorbike_mechanic',
    skills: ['Motorcycle repair', 'Japanese bikes', 'Honda', 'Yamaha', 'Engine rebuild'],
    location: 'Bangkok',
    province: 'Bangkok',
    yearsExperience: 8,
    rating: 4.7,
    completedJobs: 140,
    hourlyRate: 500,
    monthlyRate: 22_000,
    availability: 'today',
    languages: ['Thai', 'English'],
    certifications: ['Honda certified'],
    responseRate: 91,
    bio: 'Japanese motorcycle specialist. Wave, Click, PCX, and big bikes. Workshop in Lat Phrao.',
    preferredJobTypes: ['Honda service', 'Yamaha service'],
    remoteOk: false,
    responseTime: 'Usually replies in 1 hour',
    autoAcceptThreshold: 88,
    reviews: [{ id: 'r3', author: 'Nok', rating: 5, text: 'Rebuilt my Wave engine properly.', date: '2026-06-18' }],
    portfolio: [{ id: 'p3', title: 'PCX 160 full service', description: 'Scheduled maintenance and CVT.' }],
  },
  {
    id: 'fl-alex',
    userId: 'user-alex',
    name: 'Alex',
    profilePhoto: photo('alex-mechanic'),
    verified: false,
    category: 'motorbike_mechanic',
    skills: ['Motorcycle repair', 'General service', 'Tire change'],
    location: 'Chiang Mai',
    province: 'Chiang Mai',
    yearsExperience: 3,
    rating: 4.4,
    completedJobs: 32,
    hourlyRate: 350,
    monthlyRate: 15_000,
    availability: 'this_week',
    languages: ['English'],
    certifications: [],
    responseRate: 80,
    bio: 'Mobile mechanic around Chiang Mai old city. Best for general scooter work, not European specialists.',
    preferredJobTypes: ['Scooter repair'],
    remoteOk: false,
    responseTime: 'Usually replies in 3 hours',
    autoAcceptThreshold: 90,
    reviews: [{ id: 'r4', author: 'Ben', rating: 4, text: 'Good for a basic service.', date: '2026-04-09' }],
    portfolio: [{ id: 'p4', title: 'Click 125 service', description: 'Oil, filter, and brake pads.' }],
  },
  {
    id: 'fl-niran',
    userId: 'user-niran',
    name: 'Niran',
    profilePhoto: photo('niran-reg'),
    verified: true,
    category: 'vehicle_registration',
    skills: ['Vehicle registration', 'Blue book', 'Tax renewal', 'Department of Land Transport'],
    location: 'Bangkok',
    province: 'Bangkok',
    yearsExperience: 6,
    rating: 4.8,
    completedJobs: 210,
    hourlyRate: 400,
    monthlyRate: 18_000,
    availability: 'available_now',
    languages: ['Thai', 'English'],
    certifications: ['DLT process specialist'],
    responseRate: 97,
    bio: 'Handles car and motorcycle registration, plate transfer, and annual tax without the queue.',
    preferredJobTypes: ['Vehicle registration', 'Tax renewal'],
    remoteOk: false,
    responseTime: 'Usually replies in 20 minutes',
    autoAcceptThreshold: 80,
    reviews: [{ id: 'r5', author: 'Sarah M.', rating: 5, text: 'Registration done in one morning.', date: '2026-08-01' }],
    portfolio: [{ id: 'p5', title: 'Car transfer + plates', description: 'Complete ownership transfer in Bangkok.' }],
  },
  {
    id: 'fl-ploy',
    userId: 'user-ploy',
    name: 'Ploy',
    profilePhoto: photo('ploy-license'),
    verified: true,
    category: 'thai_license',
    skills: ['Thai driving license', 'Translation support', 'DLT appointment'],
    location: 'Bangkok',
    province: 'Bangkok',
    yearsExperience: 4,
    rating: 4.6,
    completedJobs: 95,
    hourlyRate: 380,
    monthlyRate: 16_000,
    availability: 'today',
    languages: ['Thai', 'English'],
    certifications: ['License application coach'],
    responseRate: 93,
    bio: 'Guides expats through Thai car and motorcycle license tests, medical certs, and DLT visits.',
    preferredJobTypes: ['Thai license'],
    remoteOk: false,
    responseTime: 'Usually replies in 45 minutes',
    autoAcceptThreshold: 84,
    reviews: [{ id: 'r6', author: 'Tom', rating: 5, text: 'Passed motorcycle license on the first try.', date: '2026-03-22' }],
    portfolio: [{ id: 'p6', title: 'Car license package', description: 'Medical, forms, and test-day support.' }],
  },
  {
    id: 'fl-kittisak',
    userId: 'user-kittisak',
    name: 'Kittisak',
    profilePhoto: photo('kittisak-driver'),
    verified: true,
    category: 'driver',
    skills: ['Private driver', 'Airport runs', 'Long distance', 'Defensive driving'],
    location: 'Bangkok',
    province: 'Bangkok',
    yearsExperience: 7,
    rating: 4.5,
    completedJobs: 160,
    hourlyRate: 300,
    monthlyRate: 18_000,
    availability: 'available_now',
    languages: ['Thai', 'English'],
    certifications: ['Public chauffeur license'],
    responseRate: 95,
    bio: 'Full-time and ad-hoc driver for families and executives. Clean record, knows Bangkok traffic.',
    preferredJobTypes: ['Full-time driver', 'Airport transfer'],
    remoteOk: false,
    responseTime: 'Usually replies in 10 minutes',
    autoAcceptThreshold: 78,
    reviews: [{ id: 'r7', author: 'Lisa', rating: 5, text: 'Punctual every morning for school runs.', date: '2026-07-28' }],
    portfolio: [{ id: 'p7', title: 'Executive monthly driver', description: 'Sukhumvit–Silom weekday coverage.' }],
  },
  {
    id: 'fl-david',
    userId: 'user-david',
    name: 'David',
    profilePhoto: photo('david-driver'),
    verified: true,
    category: 'driver',
    skills: ['Tour driver', 'Phuket routes', 'Van driving'],
    location: 'Phuket',
    province: 'Phuket',
    yearsExperience: 10,
    rating: 4.6,
    completedJobs: 220,
    hourlyRate: 350,
    monthlyRate: 22_000,
    availability: 'this_week',
    languages: ['English', 'Thai'],
    certifications: ['Tourism driver permit'],
    responseRate: 88,
    bio: 'Island driver for families and villa guests. Airport, beaches, and day trips.',
    preferredJobTypes: ['Tour driver'],
    remoteOk: false,
    responseTime: 'Usually replies in 2 hours',
    autoAcceptThreshold: 86,
    reviews: [{ id: 'r8', author: 'Helen', rating: 4, text: 'Great with kids and luggage.', date: '2026-01-14' }],
    portfolio: [{ id: 'p8', title: 'Airport + villa week', description: 'Phuket airport and west-coast villas.' }],
  },
  {
    id: 'fl-wichai',
    userId: 'user-wichai',
    name: 'Wichai',
    profilePhoto: photo('wichai-construction'),
    verified: true,
    category: 'construction',
    skills: ['Construction', 'Site supervision', 'Concrete', 'Villa finishing'],
    location: 'Phuket',
    province: 'Phuket',
    yearsExperience: 12,
    rating: 4.3,
    completedJobs: 54,
    hourlyRate: 400,
    monthlyRate: 25_000,
    availability: 'this_week',
    languages: ['Thai', 'English'],
    certifications: ['Safety supervisor'],
    responseRate: 84,
    bio: 'Construction lead for villa renovations and small commercial sites in Phuket.',
    preferredJobTypes: ['Villa renovation', 'Site crew'],
    remoteOk: false,
    responseTime: 'Usually replies in 4 hours',
    autoAcceptThreshold: 80,
    reviews: [{ id: 'r9', author: 'Mark', rating: 4, text: 'Kept the villa job on schedule.', date: '2026-02-11' }],
    portfolio: [{ id: 'p9', title: 'Kata villa fit-out', description: 'Interior finishing crew of 6.' }],
  },
  {
    id: 'fl-mali',
    userId: 'user-mali',
    name: 'Mali',
    profilePhoto: photo('mali-construction'),
    verified: false,
    category: 'construction',
    skills: ['Construction', 'Painting', 'Tiling'],
    location: 'Bangkok',
    province: 'Bangkok',
    yearsExperience: 2,
    rating: 4.1,
    completedJobs: 18,
    hourlyRate: 280,
    monthlyRate: 14_000,
    availability: 'available_now',
    languages: ['Thai'],
    certifications: [],
    responseRate: 76,
    bio: 'Junior construction helper available immediately in greater Bangkok.',
    preferredJobTypes: ['Helper', 'Painting'],
    remoteOk: false,
    responseTime: 'Usually replies in 6 hours',
    autoAcceptThreshold: 70,
    reviews: [{ id: 'r10', author: 'Gai', rating: 4, text: 'Hard worker, still learning English.', date: '2026-06-01' }],
    portfolio: [{ id: 'p10', title: 'Condo paint job', description: 'Two-bedroom condo in Rama 9.' }],
  },
  {
    id: 'fl-anong',
    userId: 'user-anong',
    name: 'Anong',
    profilePhoto: photo('anong-visa'),
    verified: true,
    category: 'visa',
    skills: ['Visa', 'Work permit', 'Immigration', '90-day report'],
    location: 'Bangkok',
    province: 'Bangkok',
    yearsExperience: 9,
    rating: 4.9,
    completedJobs: 310,
    hourlyRate: 650,
    monthlyRate: 30_000,
    availability: 'today',
    languages: ['Thai', 'English'],
    certifications: ['Immigration liaison'],
    responseRate: 99,
    bio: 'Visa and work-permit specialist for companies and families. One-One-One and Chaeng Wattana.',
    preferredJobTypes: ['Visa', 'Work permit'],
    remoteOk: true,
    responseTime: 'Usually replies in 10 minutes',
    autoAcceptThreshold: 83,
    reviews: [{ id: 'r11', author: 'Daniel', rating: 5, text: 'Non-B extension without stress.', date: '2026-08-19' }],
    portfolio: [{ id: 'p11', title: 'Company work permits', description: 'Batch of 8 permits for a startup.' }],
  },
  {
    id: 'fl-somsak',
    userId: 'user-somsak',
    name: 'Somsak',
    profilePhoto: photo('somsak-legal'),
    verified: true,
    category: 'legal',
    skills: ['Contracts', 'Company law', 'Property', 'Thai-English legal'],
    location: 'Bangkok',
    province: 'Bangkok',
    yearsExperience: 15,
    rating: 4.8,
    completedJobs: 75,
    hourlyRate: 1200,
    monthlyRate: 45_000,
    availability: 'this_week',
    languages: ['Thai', 'English'],
    certifications: ['Thai Barrister'],
    responseRate: 90,
    bio: 'Commercial and property lawyer for SMEs and expats. Clear retainers, no surprise fees.',
    preferredJobTypes: ['Contract review', 'Company setup'],
    remoteOk: true,
    responseTime: 'Usually replies in 2 hours',
    autoAcceptThreshold: 92,
    reviews: [{ id: 'r12', author: 'Elena', rating: 5, text: 'Precise contract markup overnight.', date: '2026-05-30' }],
    portfolio: [{ id: 'p12', title: 'Shareholder agreement', description: 'Bilingual SHA for a Bangkok JV.' }],
  },
  {
    id: 'fl-emma',
    userId: 'user-emma',
    name: 'Emma Chen',
    profilePhoto: photo('emma-interpreter'),
    verified: true,
    category: 'interpreter',
    skills: ['Interpreting', 'English', 'Thai', 'Chinese', 'Business meetings'],
    location: 'Bangkok',
    province: 'Bangkok',
    yearsExperience: 6,
    rating: 4.9,
    completedJobs: 128,
    hourlyRate: 800,
    monthlyRate: 28_000,
    availability: 'available_now',
    languages: ['English', 'Thai', 'Chinese'],
    certifications: ['Conference interpreter'],
    responseRate: 96,
    bio: 'Thai–English–Mandarin interpreter for medical, legal, and corporate meetings in Bangkok.',
    preferredJobTypes: ['Conference', 'Medical interpreting'],
    remoteOk: true,
    responseTime: 'Usually replies in 20 minutes',
    autoAcceptThreshold: 80,
    reviews: [{ id: 'r13', author: 'Hospital BD', rating: 5, text: 'Flawless medical consecutive interpreting.', date: '2026-07-03' }],
    portfolio: [{ id: 'p13', title: 'Board meeting, 3 languages', description: 'Half-day consecutive interpreting.' }],
  },
  {
    id: 'fl-nattapong',
    userId: 'user-nattapong',
    name: 'Nattapong',
    profilePhoto: photo('nattapong-interpreter'),
    verified: true,
    category: 'interpreter',
    skills: ['Interpreting', 'English', 'Thai', 'Community interpreting'],
    location: 'Chiang Mai',
    province: 'Chiang Mai',
    yearsExperience: 4,
    rating: 4.6,
    completedJobs: 67,
    hourlyRate: 500,
    monthlyRate: 18_000,
    availability: 'today',
    languages: ['Thai', 'English'],
    certifications: ['Community interpreter'],
    responseRate: 92,
    bio: 'English/Thai interpreter based in Chiang Mai. Government offices, hospitals, and property viewings.',
    preferredJobTypes: ['On-site interpreting'],
    remoteOk: true,
    responseTime: 'Usually replies in 30 minutes',
    autoAcceptThreshold: 76,
    reviews: [{ id: 'r14', author: 'Claire', rating: 5, text: 'Made land-office paperwork easy.', date: '2026-04-21' }],
    portfolio: [{ id: 'p14', title: 'Land office day', description: 'Title search + interpreting.' }],
  },
  {
    id: 'fl-peak',
    userId: 'user-peak',
    name: 'Peak',
    profilePhoto: photo('peak-fitness'),
    verified: true,
    category: 'fitness',
    skills: ['Personal training', 'Strength', 'HIIT', 'Nutrition basics'],
    location: 'Bangkok',
    province: 'Bangkok',
    yearsExperience: 5,
    rating: 4.7,
    completedJobs: 90,
    hourlyRate: 700,
    monthlyRate: 20_000,
    availability: 'available_now',
    languages: ['Thai', 'English'],
    certifications: ['NASM CPT'],
    responseRate: 94,
    bio: 'Mobile trainer for condos and parks in central Bangkok. Programs for busy professionals.',
    preferredJobTypes: ['Personal training'],
    remoteOk: true,
    responseTime: 'Usually replies in 25 minutes',
    autoAcceptThreshold: 85,
    reviews: [{ id: 'r15', author: 'Anne', rating: 5, text: 'Lost 6kg without living in the gym.', date: '2026-06-08' }],
    portfolio: [{ id: 'p15', title: '12-week strength plan', description: 'Home gym in Asok.' }],
  },
  {
    id: 'fl-sakda',
    userId: 'user-sakda',
    name: 'Sakda',
    profilePhoto: photo('sakda-boxing'),
    verified: true,
    category: 'boxing',
    skills: ['Muay Thai', 'Boxing', 'Pad work', 'Fighter conditioning'],
    location: 'Bangkok',
    province: 'Bangkok',
    yearsExperience: 11,
    rating: 4.9,
    completedJobs: 200,
    hourlyRate: 900,
    monthlyRate: 35_000,
    availability: 'today',
    languages: ['Thai', 'English'],
    certifications: ['Camp head trainer'],
    responseRate: 89,
    bio: 'Former stadium fighter coaching beginners through amateurs. Pads, clinch, and fight IQ.',
    preferredJobTypes: ['Private pads', 'Camp coaching'],
    remoteOk: false,
    responseTime: 'Usually replies in 1 hour',
    autoAcceptThreshold: 88,
    reviews: [{ id: 'r16', author: 'Ryan', rating: 5, text: 'Best pads I have had in Bangkok.', date: '2026-08-05' }],
    portfolio: [{ id: 'p16', title: 'Amateur fight camp', description: '8-week camp, two fighters.' }],
  },
  {
    id: 'fl-lek',
    userId: 'user-lek',
    name: 'Lek',
    profilePhoto: photo('lek-translator'),
    verified: true,
    category: 'translator',
    skills: ['Translation', 'Certified translation', 'Thai', 'English', 'Legal documents'],
    location: 'Bangkok',
    province: 'Bangkok',
    yearsExperience: 8,
    rating: 4.5,
    completedJobs: 240,
    hourlyRate: 550,
    monthlyRate: 24_000,
    availability: 'this_week',
    languages: ['Thai', 'English'],
    certifications: ['Certified translator'],
    responseRate: 91,
    bio: 'Certified Thai–English translator for visas, contracts, and academic documents.',
    preferredJobTypes: ['Certified translation'],
    remoteOk: true,
    responseTime: 'Usually replies in 1 hour',
    autoAcceptThreshold: 82,
    reviews: [{ id: 'r17', author: 'Embassy client', rating: 4, text: 'Accurate certified packet.', date: '2026-03-17' }],
    portfolio: [{ id: 'p17', title: 'Marriage certificate set', description: 'Certified EN/TH with notary.' }],
  },
  {
    id: 'fl-arthit',
    userId: 'user-arthit',
    name: 'Arthit',
    profilePhoto: photo('arthit-electrician'),
    verified: true,
    category: 'electrician',
    skills: ['Electrical', 'Condo wiring', 'Breaker panels', 'Safety inspection'],
    location: 'Bangkok',
    province: 'Bangkok',
    yearsExperience: 7,
    rating: 4.6,
    completedJobs: 110,
    hourlyRate: 450,
    monthlyRate: 19_000,
    availability: 'available_now',
    languages: ['Thai', 'English'],
    certifications: ['Licensed electrician'],
    responseRate: 93,
    bio: 'Licensed electrician for condos and small shops. Same-day call-outs in Bangkok.',
    preferredJobTypes: ['Emergency electrical', 'Fit-out'],
    remoteOk: false,
    responseTime: 'Usually replies in 20 minutes',
    autoAcceptThreshold: 79,
    reviews: [{ id: 'r18', author: 'Bee', rating: 5, text: 'Fixed a dangerous panel the same night.', date: '2026-07-21' }],
    portfolio: [{ id: 'p18', title: 'Cafe fit-out', description: 'New circuits and lighting.' }],
  },
  {
    id: 'fl-yai',
    userId: 'user-yai',
    name: 'Yai',
    profilePhoto: photo('yai-plumber'),
    verified: true,
    category: 'plumber',
    skills: ['Plumbing', 'Leak detection', 'Water heater', 'Bathroom renovation'],
    location: 'Chiang Mai',
    province: 'Chiang Mai',
    yearsExperience: 9,
    rating: 4.4,
    completedJobs: 88,
    hourlyRate: 380,
    monthlyRate: 17_000,
    availability: 'today',
    languages: ['Thai', 'English'],
    certifications: ['Plumbing technician'],
    responseRate: 87,
    bio: 'Plumber covering Chiang Mai city and Hang Dong. Leaks, pumps, and bathroom work.',
    preferredJobTypes: ['Leak repair'],
    remoteOk: false,
    responseTime: 'Usually replies in 90 minutes',
    autoAcceptThreshold: 81,
    reviews: [{ id: 'r19', author: 'Paul', rating: 4, text: 'Found a hidden leak under the tiles.', date: '2026-05-12' }],
    portfolio: [{ id: 'p19', title: 'Villa pump replace', description: 'Booster pump and pressure tank.' }],
  },
  {
    id: 'fl-fern',
    userId: 'user-fern',
    name: 'Fern',
    profilePhoto: photo('fern-design'),
    verified: true,
    category: 'graphic_designer',
    skills: ['Graphic design', 'Branding', 'Social kits', 'Packaging'],
    location: 'Bangkok',
    province: 'Bangkok',
    yearsExperience: 4,
    rating: 4.8,
    completedJobs: 72,
    hourlyRate: 600,
    monthlyRate: 22_000,
    availability: 'this_week',
    languages: ['Thai', 'English'],
    certifications: [],
    responseRate: 97,
    bio: 'Brand and social designer for F&B and hospitality. Remote-friendly, Bangkok based.',
    preferredJobTypes: ['Brand identity', 'Social media'],
    remoteOk: true,
    responseTime: 'Usually replies in 15 minutes',
    autoAcceptThreshold: 84,
    reviews: [{ id: 'r20', author: 'Cafe owner', rating: 5, text: 'Menu and logo felt premium.', date: '2026-08-11' }],
    portfolio: [{ id: 'p20', title: 'Cafe rebrand', description: 'Logo, menu, and IG templates.' }],
  },
  {
    id: 'fl-pat',
    userId: 'user-pat',
    name: 'Pat',
    profilePhoto: photo('pat-web'),
    verified: true,
    category: 'web_developer',
    skills: ['Web development', 'React', 'Next.js', 'TypeScript', 'Landing pages'],
    location: 'Bangkok',
    province: 'Bangkok',
    yearsExperience: 6,
    rating: 4.7,
    completedJobs: 41,
    hourlyRate: 1200,
    monthlyRate: 40_000,
    availability: 'this_week',
    languages: ['Thai', 'English'],
    certifications: [],
    responseRate: 90,
    bio: 'Product-minded web developer. Marketing sites and booking flows for Thai SMEs.',
    preferredJobTypes: ['Marketing site', 'Web app'],
    remoteOk: true,
    responseTime: 'Usually replies in 2 hours',
    autoAcceptThreshold: 90,
    reviews: [{ id: 'r21', author: 'Founder', rating: 5, text: 'Shipped a booking site in two weeks.', date: '2026-06-25' }],
    portfolio: [{ id: 'p21', title: 'Clinic booking site', description: 'Next.js + calendar integration.' }],
  },
];

export const PREBUILT_DEMO_JOBS: Job[] = [
  {
    id: 'demo-job-mechanic',
    clientId: DEMO_CLIENT.id,
    clientName: DEMO_CLIENT.name,
    category: 'motorbike_mechanic',
    title: 'Motorbike mechanic needed in Bangkok',
    description: 'Need a Vespa mechanic in Bangkok ASAP. Budget around ฿20,000. Must service Vespa and European motorcycles.',
    location: 'Bangkok',
    province: 'Bangkok',
    locationMode: 'onsite',
    budgetMin: 15_000,
    budgetMax: 20_000,
    urgency: 'asap',
    specificDate: null,
    requiredSkills: ['Vespa', 'Motorcycle repair', 'European motorcycles'],
    experienceRequired: '3+',
    languages: ['English', 'Thai'],
    remoteOk: false,
    status: 'open',
    createdAt: '2026-09-01T02:00:00.000Z',
    sourceText: 'Need a Vespa mechanic in Bangkok ASAP. Budget ฿20,000.',
  },
  {
    id: 'demo-job-interpreter',
    clientId: DEMO_CLIENT.id,
    clientName: DEMO_CLIENT.name,
    category: 'interpreter',
    title: 'Thai-English interpreter in Bangkok',
    description: 'Need an English/Thai interpreter in Bangkok tomorrow for a hospital appointment.',
    location: 'Bangkok',
    province: 'Bangkok',
    locationMode: 'onsite',
    budgetMin: 8_000,
    budgetMax: 18_000,
    urgency: 'today',
    specificDate: 'Tomorrow',
    requiredSkills: ['Interpreting', 'English', 'Thai'],
    experienceRequired: '3+',
    languages: ['English', 'Thai'],
    remoteOk: false,
    status: 'open',
    createdAt: '2026-09-01T02:05:00.000Z',
    sourceText: 'Need a Thai-English interpreter in Bangkok tomorrow.',
  },
  {
    id: 'demo-job-construction',
    clientId: 'client-villa',
    clientName: 'Villa Phuket Co.',
    category: 'construction',
    title: 'Construction worker in Phuket this week',
    description: 'Need a construction crew lead in Phuket this week for villa finishing work.',
    location: 'Phuket',
    province: 'Phuket',
    locationMode: 'onsite',
    budgetMin: 18_000,
    budgetMax: 28_000,
    urgency: 'this_week',
    specificDate: null,
    requiredSkills: ['Construction', 'Villa finishing'],
    experienceRequired: '5+',
    languages: ['Thai'],
    remoteOk: false,
    status: 'open',
    createdAt: '2026-09-01T02:10:00.000Z',
    sourceText: 'Need a construction worker in Phuket this week.',
  },
  {
    id: 'demo-job-driver',
    clientId: DEMO_CLIENT.id,
    clientName: DEMO_CLIENT.name,
    category: 'driver',
    title: 'Full-time driver in Bangkok',
    description: 'Looking for a full-time private driver in Bangkok. Flexible start date.',
    location: 'Bangkok',
    province: 'Bangkok',
    locationMode: 'onsite',
    budgetMin: 16_000,
    budgetMax: 22_000,
    urgency: 'flexible',
    specificDate: null,
    requiredSkills: ['Private driver', 'Full-time driver'],
    experienceRequired: '3+',
    languages: ['Thai', 'English'],
    remoteOk: false,
    status: 'open',
    createdAt: '2026-09-01T02:15:00.000Z',
    sourceText: 'Need a driver in Bangkok full time.',
  },
  {
    id: 'demo-job-registration',
    clientId: DEMO_CLIENT.id,
    clientName: DEMO_CLIENT.name,
    category: 'vehicle_registration',
    title: 'Vehicle registration specialist in Bangkok',
    description: 'Need someone to handle car registration and blue book transfer in Bangkok.',
    location: 'Bangkok',
    province: 'Bangkok',
    locationMode: 'onsite',
    budgetMin: 10_000,
    budgetMax: 18_000,
    urgency: 'asap',
    specificDate: null,
    requiredSkills: ['Vehicle registration', 'Blue book'],
    experienceRequired: '1+',
    languages: ['Thai', 'English'],
    remoteOk: false,
    status: 'open',
    createdAt: '2026-09-01T02:20:00.000Z',
    sourceText: 'Need a vehicle registration specialist in Bangkok.',
  },
  {
    id: 'demo-job-interpreter-cnx',
    clientId: 'client-cnx',
    clientName: 'Chiang Mai Relocation',
    category: 'interpreter',
    title: 'English/Thai interpreter in Chiang Mai',
    description: 'Need an English/Thai interpreter in Chiang Mai for land office and hospital visits.',
    location: 'Chiang Mai',
    province: 'Chiang Mai',
    locationMode: 'onsite',
    budgetMin: 10_000,
    budgetMax: 20_000,
    urgency: 'today',
    specificDate: null,
    requiredSkills: ['Interpreting', 'English', 'Thai'],
    experienceRequired: '1+',
    languages: ['English', 'Thai'],
    remoteOk: false,
    status: 'open',
    createdAt: '2026-09-01T02:25:00.000Z',
    sourceText: 'Need an English/Thai interpreter in Chiang Mai.',
  },
];

export const DEMO_JOB_PRESETS = [
  { id: 'demo-job-mechanic', label: 'Motorbike mechanic · Bangkok · ASAP · ฿20,000' },
  { id: 'demo-job-interpreter', label: 'Thai-English interpreter · Bangkok · Tomorrow' },
  { id: 'demo-job-construction', label: 'Construction worker · Phuket · This week' },
  { id: 'demo-job-driver', label: 'Driver · Bangkok · Full time' },
  { id: 'demo-job-registration', label: 'Vehicle registration specialist · Bangkok' },
] as const;
