import type { RealEstateListing } from './real-estate.types';

/** Local fallback inventory — mirrors SiamEZwebNG sample listings. */
export const seedRealEstateListings: RealEstateListing[] = [
  {
    id: 'sukhumvit-condo-2br-sale',
    ownerId: 'seed-admin',
    title: 'Modern 2-Bedroom Condo near BTS Asok',
    propertyType: 'condo',
    listingType: 'sale',
    bedrooms: 2,
    bathrooms: 2,
    areaSqm: 68,
    landAreaSqm: null,
    floor: 22,
    yearBuilt: 2019,
    province: 'Bangkok',
    district: 'Khlong Toei',
    neighborhood: 'Asok',
    priceAmount: 8_900_000,
    priceCurrency: 'THB',
    sellerKind: 'dealer',
    furnished: 'furnished',
    status: 'available',
    heroImageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80',
    description:
      'Bright corner unit with city views, full furniture package, and pool/gym access. Walking distance to BTS Asok and Terminal 21. Ideal for owner-occupiers or rental investors.',
    isBoosted: true,
    boostActive: true,
    createdAt: '2026-05-01T10:00:00.000Z',
  },
  {
    id: 'chiang-mai-pool-villa-sale',
    ownerId: 'seed-admin',
    title: '4-Bedroom Pool Villa in Hang Dong',
    propertyType: 'villa',
    listingType: 'sale',
    bedrooms: 4,
    bathrooms: 4,
    areaSqm: 320,
    landAreaSqm: 800,
    floor: null,
    yearBuilt: 2016,
    province: 'Chiang Mai',
    district: 'Hang Dong',
    neighborhood: 'Ban Waen',
    priceAmount: 14_500_000,
    priceCurrency: 'THB',
    sellerKind: 'private',
    furnished: 'partially',
    status: 'available',
    heroImageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80',
    description:
      'Spacious tropical villa with private pool, covered parking for two cars, and landscaped garden. Quiet residential pocket with easy access to Hang Dong Road and international schools.',
    createdAt: '2026-05-02T10:00:00.000Z',
  },
  {
    id: 'phuket-townhouse-rent',
    ownerId: 'seed-admin',
    title: '3-Bedroom Townhouse for Rent near Central Phuket',
    propertyType: 'townhouse',
    listingType: 'rent',
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 180,
    landAreaSqm: 120,
    floor: null,
    yearBuilt: 2018,
    province: 'Phuket',
    district: 'Kathu',
    neighborhood: 'Kathu',
    priceAmount: 45_000,
    priceCurrency: 'THB',
    sellerKind: 'dealer',
    furnished: 'furnished',
    status: 'available',
    heroImageUrl: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=1600&q=80',
    description:
      'Fully furnished townhouse ready for move-in. Close to Central Festival Phuket, shops, and restaurants. Includes Wi-Fi, cable TV, and weekly garden service. Minimum 12-month lease.',
    createdAt: '2026-05-03T10:00:00.000Z',
  },
  {
    id: 'pattaya-beachfront-condo-rent',
    ownerId: 'seed-admin',
    title: 'Sea-View Studio Condo for Rent in Jomtien',
    propertyType: 'condo',
    listingType: 'rent',
    bedrooms: 0,
    bathrooms: 1,
    areaSqm: 38,
    landAreaSqm: null,
    floor: 15,
    yearBuilt: 2021,
    province: 'Chonburi',
    district: 'Bang Lamung',
    neighborhood: 'Jomtien',
    priceAmount: 22_000,
    priceCurrency: 'THB',
    sellerKind: 'private',
    furnished: 'furnished',
    status: 'available',
    heroImageUrl: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1600&q=80',
    description:
      'Compact studio with balcony sea view, swimming pool, and 24-hour security. Perfect for long-stay visitors or remote workers. Walking distance to Jomtien Beach and cafes.',
    isBoosted: true,
    boostActive: true,
    createdAt: '2026-05-04T10:00:00.000Z',
  },
  {
    id: 'hua-hin-land-sale',
    ownerId: 'seed-admin',
    title: '1 Rai Chanote Land near Hua Hin Town',
    propertyType: 'land',
    listingType: 'sale',
    bedrooms: null,
    bathrooms: null,
    areaSqm: 1600,
    landAreaSqm: 1600,
    floor: null,
    yearBuilt: null,
    province: 'Prachuap Khiri Khan',
    district: 'Hua Hin',
    neighborhood: 'Nong Kae',
    priceAmount: 6_200_000,
    priceCurrency: 'THB',
    sellerKind: 'dealer',
    furnished: 'not_applicable',
    status: 'available',
    heroImageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80',
    description:
      'Flat rectangular plot with Chanote title, road access, and utilities nearby. Suitable for a holiday home or small development. About 15 minutes to Hua Hin beach and night market.',
    createdAt: '2026-05-05T10:00:00.000Z',
  },
  {
    id: 'silom-office-commercial-sale',
    ownerId: 'seed-admin',
    title: 'Ground-Floor Commercial Unit on Silom Road',
    propertyType: 'commercial',
    listingType: 'sale',
    bedrooms: null,
    bathrooms: 2,
    areaSqm: 95,
    landAreaSqm: null,
    floor: 1,
    yearBuilt: 2012,
    province: 'Bangkok',
    district: 'Bang Rak',
    neighborhood: 'Silom',
    priceAmount: 18_500_000,
    priceCurrency: 'THB',
    sellerKind: 'dealer',
    furnished: 'unfurnished',
    status: 'available',
    heroImageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=80',
    description:
      'Street-facing commercial space with high foot traffic near BTS Sala Daeng. Suitable for retail, cafe, or service business. Includes one parking allocation.',
    createdAt: '2026-05-06T10:00:00.000Z',
  },
];
